version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - mynetwork

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-container
    ports:
      - 5000:5000
    networks:
      - mynetwork
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb-container:27017

networks:
  mynetwork:

volumes:
  mongodb-data:
